name: Peter Sputnik
favicon: null
layout_spectrum: 0.989461587741971
typography_spectrum: 0.9752659376244992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3092251403722912
  lightness: 0.49339069379493594
  saturation: 0.6847473459783942
  rhythmicContrast: 0.75
purpose: []
